dont fail if the auto-update/context.tf branch already exists

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -15,30 +15,39 @@ runs:
       id: update
       env:
         GITHUB_TOKEN: "${{ inputs.token }}"
+        BRANCH_NAME: "auto-update/context.tf"
       run: |
         if [[ -f context.tf ]]; then
-          echo "Discovered existing context.tf! Fetching most recent version to see if there is an update."
-          curl -o context.tf -fsSL https://raw.githubusercontent.com/cloudposse/terraform-null-label/master/exports/context.tf
-          if git diff --no-patch --exit-code context.tf; then
-            echo "No changes detected! Exiting the job..."
+          echo "Discovered existing context.tf!"
+          echo "Checking for pre-existing ${BRANCH_NAME} branch."
+          if ! [[ git rev-parse --quiet --verify ${BRANCH_NAME} > /dev/null ]]; then
+            echo "Branch ${BRANCH_NAME} not found."
+            echo "Fetching most recent version of context.tf to see if there is an update."
+            curl -o context.tf -fsSL https://raw.githubusercontent.com/cloudposse/terraform-null-label/master/exports/context.tf
+            if git diff --no-patch --exit-code context.tf; then
+              echo "No changes detected! Exiting the job..."
+            else
+              # updating context.tf and documentation
+              echo "context.tf file has changed. Update examples and rebuild README.md and commit everything to a new ${BRANCH_NAME} branch."
+              make init
+              make github/init/context.tf
+              make readme/build
+              # moving to new branch to commit changes
+              git branch -avv
+              git checkout -b auto-update/context.tf
+              git branch -avv
+              # committing changes
+              git config --global user.name 'cloudpossebot'
+              git config --global user.email '11232728+cloudpossebot@users.noreply.github.com'
+              git add -A
+              git commit -m "Update context.tf from origin source"
+              git push --set-upstream origin ${BRANCH_NAME}
+              # setting flag to create pull request for new branch
+              echo "::set-output name=create_pull_request::true"
+            fi
           else
-            # updating context.tf and documentation
-            echo "context.tf file has changed. Update examples and rebuild README.md."
-            make init
-            make github/init/context.tf
-            make readme/build
-            # moving to new branch to commit changes
-            git branch -avv
-            git checkout -b auto-update/context.tf
-            git branch -avv
-            # committing changes
-            git config --global user.name 'cloudpossebot'
-            git config --global user.email '11232728+cloudpossebot@users.noreply.github.com'
-            git add -A
-            git commit -m "Update context.tf from origin source"
-            git push --set-upstream origin auto-update/context.tf
-            # setting flag to create pull request for new branch
-            echo "::set-output name=create_pull_request::true"
+            echo "Branch ${BRANCH_NAME} found."
+            echo "Please merge pre-existing ${BRANCH_NAME} branch before rerunning this action."
           fi
         else
           echo "This module has not yet been updated to support the context.tf pattern! Please update in order to support automatic updates."
